services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=contact@pplethai.org"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  krayin-php-apache:
    build:
      args:
        container_project_path: /var/www/html/
        uid: 1001
        user: $USER
      context: .
      dockerfile: ./Dockerfile
    image: krayin-php-apache
    ports:
      - 8000:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.krayin.rule=Host(`crm.pplethai.org`)"
      - "traefik.http.routers.krayin.entrypoints=websecure"
      - "traefik.http.routers.krayin.tls=true"
      - "traefik.http.routers.krayin.tls.certresolver=letsencrypt"
    volumes:
      - ./:/var/www/html/krayin/

  krayin-mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql/

  krayin-redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

  krayin-phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: krayin-mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 512M
    ports:
      - 8080:80

  krayin-mailhog:
    image: mailhog/mailhog
    logging:
      # Disable saving logs.
      driver: "none"
    ports:
      # SMTP server.
      - 1025:1025
      - 8025:8025
volumes:
  mysql_data:
  redis_data:
